### ISSUE TITLE
Intention to contribute and add more methods

### ISSUE THREAD

**Issue by juliohm** [xukai92/DensityRatioEstimation.jl#10]
Hi @xukai92, thank you for sharing this package. I was about to start one myself, but found yours. :)

Could you please elaborate on the MMD method that is already implemented? Do you have a specific paper that you could share? The book by Sugiyama et al. is broad on the theme, and I would like to contribute other methods therein.

I have the Kulback-Leibler Importance Estimation Procedure (KLIEP) method implemented at the moment, and was also looking into the Kernel Mean Matching (KMM).

**Comment by xukai92** [comment]
Hi @juliohm, thanks for your interests.

The MMD method I implemented is from Chapter 3 of Sugiyama's book (https://www.cambridge.org/core/books/density-ratio-estimation-in-machine-learning/moment-matching/C65B5641C9E4CE7A2A379316D4F731F3); to be more specific, the KMM method in Section 3.3.1.

I'd like to work together to putting more methods in this package. Especially I think it would be nice to have discussion on things like interfaces, which is purly based on my own preference.

Maybe you can start a PR with the KLIEP implementation and we can discuss over there?

**Comment by juliohm** [comment]
Thank you @xukai92 , let's work together on this then. This interface should handle n-dimensional feature spaces, and also iterable objects of features as opposed to big matrices with pre-allocated features. I will close this issue and open a new one to discuss interface. 👍
