### ISSUE TITLE
Tag a new version

### ISSUE THREAD

**Issue by juliohm** [xukai92/DensityRatioEstimation.jl#18]
Can I tag a new version of the project @xukai92? Did you have a chance to look into the KMM implementations?

**Comment by xukai92** [comment]
Feel free to make new tags. 

The CPU implementation looks fine to me. I will make another PR to fix the GPU compatibility next week.

**Comment by juliohm** [comment]
Thanks, will do. 👍

**Comment by juliohm** [comment]
Just sharing a script that I used to test KMM, the result doesn't look very good to me, but I am not used to the KMM results. Only familiar with KLIEP:

```julia
using DensityRatioEstimation
using Distributions
using Random
using Plots

function plot_d_nu(pair, x_de, r̂)
  # extract pair
  d_nu, d_de = pair

  # sort vectors for plotting
  inds = sortperm(x_de)
  xs = x_de[inds]
  r̂s = r̂[inds]

  # actual and estimated d_nu
  ps = pdf.(d_nu, xs)
  p̂s = r̂s .* pdf.(d_de, xs)

  plot(xs, ps, label="d_nu (actual)")
  plot!(xs, p̂s, label="d_nu (estimate)")
end

pair₁ = Normal(1,1), Normal(0,2)
d_nu, d_de = pair₁

Random.seed!(123)
x_nu, x_de = rand(d_nu, 2000), rand(d_de, 1000)

# estimated density ratio
σ, B, ϵ, λ = 1.0, Inf, 0.0, 0.001
r̂ = densratio(x_nu, x_de, KMM(σ=σ, B=B, ϵ=ϵ, λ=λ), optlib=JuliaLib)

plot_d_nu(pair₁, x_de, r̂)
```

If you replace the estimator with KLIEP, the plot looks more reasonable like in our test suite.

**Comment by xukai92** [comment]
Thanks for the double checking. There is actually a bug, fixed here https://github.com/xukai92/DensityRatioEstimation.jl/pull/19. I only used the method for `n_nu == n_de`, for which reason I didn't find it.
