### ISSUE TITLE
Implement available_optlib

### ISSUE THREAD

**Issue by xukai92** [xukai92/DensityRatioEstimation.jl#25]
Do you think it's a good idea to have `available_optlib` for each method?

**Comment by juliohm** [comment]
Good idea :100: We could possibly automate it too using Julia's metaprogramming features. :+1: We can follow the simple approach for the moment by defining the methods manually as we do with `default_optlib`. Would you like to work on it?

Please make sure we can query the instances of estimators as well as their type, like it is done with `default_optlib`.
