### ISSUE TITLE
Invitation to JuliaEarth organization

### ISSUE THREAD

**Issue by juliohm** [xukai92/DensityRatioEstimation.jl#26]
Hi @xukai92,

I've created an organization where I am migrating all my statistical packages to a common umbrella in the Earth sciences, and would like to know if you are interested in being part of it? I've migrated two packages so far, but there are at least 10 more to migrate over the week: https://github.com/JuliaEarth

The umbrella has the benefit of attracting more contributors as we discussed in another thread, and I think there are at least 3 people this time, including you, with good statistical background that could join. I'm currently sending the invitations.

If you feel that this is a good idea, please let me know, and we can migrate this package there as well. Putting it there would help formalizing teams, and would help solve this issue that potential contributors do not contribute code with the fear that they won't receive proper credit for it.

Migrating it there has one potential issue that I would like to discuss with you. Ideally all packages in the org will follow a single style guide, and these ~15 packages that I am migrating there already have a common style that is different than the one we are working here. Particularly, they have 2 whitespaces as opposed to 4. Other than that our style guide here matches with the one there so far. As a side note, our current codebase here has 2 whitespaces, so no need for additional changes before performing the migration.

Have a good night, calling the day here.

**Comment by xukai92** [comment]
Thanks for the invitation. I really hope this package could go to some organization for better contribution. My main concern is that whether or not JuliaEarth is the correct home for this package? I feel the ideal place should be JuliaStats.

PS: for the 2 vs 4 whitespaces thing, I'm fine with 2 whitespaces if we decide to move it to JuliaEarth :)

**Comment by juliohm** [comment]
> My main concern is that whether or not JuliaEarth is the correct home for this package? I feel the ideal place should be JuliaStats.

That makes sense. We don't have membership in JuliaStats though to migrate it there. If you feel that this is easy to do, we can try contact the JuliaStats maintainers to see if they are fine with the migration.

I've finished the migration of the core projects to JuliaEarth already, and so you can have an idea of the nature of the work happening there. Now I only need to migrate some solvers for the GeoStats.jl problems.

**Comment by juliohm** [comment]
What do you think about this @xukai92 ? Would you like to move it to JuliaStats after contacting the members there? The name JuliaEarth is a little misleading, I couldn't find a better name for statistics applied to Earth sciences.

**Comment by xukai92** [comment]
I will give a try to contact JuliaStats people.

**Comment by juliohm** [comment]
Closing this issue. Please let me know if you didn't have success with the contact.

**Comment by juliohm** [comment]
Hi @xukai92 were you able to contact people in JuliaStats?

**Comment by juliohm** [comment]
May I ask you to please share with them the fact that I am also an author? I think I will lose write access if you migrate the package over there since I am not a member of JuliaStats yet.

**Comment by juliohm** [comment]
I've asked people in JuliaStats if they had interest in moving the package there. There is no interest from their side. We can consider migrating the package to JuliaEarth as suggested, or create a new organization just for this. I tend to think of the former option as a better option. Even though the name JuliaEarth is not necessarily reflecting "stats" in it, the org is quite heavy on advanced stats. In particular, density ratio estimation is becoming an integral part of the research therein at large-scale datasets. The idea would be to add you as a member in the org, and setup a team to drive the project. Can we proceed with this option? I feel that I am doing a lot of work in your personal account.

**Comment by xukai92** [comment]
The JuliaEarth option sounds good to me. Let's go for this one!

**Comment by juliohm** [comment]
Great! I sent you the invitation to the org already. Meanwhile, if you prefer, you can transfer the repo to me, and I can transfer it to the org and setup the links, bots, etc. Another related question: do you mind changing the license to [ISC](https://opensource.org/licenses/ISC)? It is equivalent to MIT, just a modernised version of it with less text. You can double check the equivalence on Wikipedia for example: https://en.wikipedia.org/wiki/ISC_license I am asking because all projects in the org currently are ISC, no problem keeping it MIT, just to be consistent :)

**Comment by juliohm** [comment]
P.S.: please read the guidelines in the org after you accept the invitation and see if everything is ok. 👍

**Comment by xukai92** [comment]
Thanks. I attempted to transfer it to the org and seems that I don't have permission on creating new public repo yet. I will transfer it to you then.

About the license, I'm happy to change it to ISC :)

**Comment by xukai92** [comment]
Just made a transfer request. Free feel to adapt it to the org. Let's improve the package together within the org in the future!

**Comment by juliohm** [comment]
Awesome! Will take care of it when I find some time here. Thanks for the
transfer! Let's improve it from there. +1

**Comment by juliohm** [comment]
Done. Can you please make your membership public in JuliaEarth? I will proceed with the PR to the general registry to update the link, and other minor changes.
